project 'EscapeGame.xcodeproj'

# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'
use_frameworks!

target 'EscapeGame' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  pod 'EstimoteSDK'
  # Pods for EscapeGame

end
