module.exports = {
	DISCONNECT: 'disconnect',
	CONNECT_SERVER: 'connection',
	CONNECT_CLIENT: 'connect',
	ONLINE: 'online',
	PI: 'sendToPi',
	PI_RESET: 'piReset',
	GAME_CANCEL: 'game_cancel',
	BEACON: 'beacon',
	INPUT: 'input',
	EVENT_START: 'event_start',
	EVENT_END: 'event_end',
	EVENT_DATA: 'event_data',
	EVENT_FINISH: 'event_finish',
	DETECTION_FIND: 'detection_find',
	DETECTION_FOUND: 'detection_found',
	RECALCULATE_START: 'recalculate_start',
	RECALCULATE_DONE: 'recalculate_done',
	IMAGE: 'image',
	BEACONS: 'beacons',
	ADD_ANSWERDATA: 'add_answerData'
};
